// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATV1DgIpplhUiy8XlQhgIzf3ZEn8WTesg',
    appId: '1:271736423528:web:4dd99442efdc79eff7e7dd',
    messagingSenderId: '271736423528',
    projectId: 'ecoearn-7c0ca',
    authDomain: 'ecoearn-7c0ca.firebaseapp.com',
    storageBucket: 'ecoearn-7c0ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnPG9GG7UqhMDaZxgHfWEI9mSpWOe9qs8',
    appId: '1:271736423528:android:2cd70ec6fc23c5bcf7e7dd',
    messagingSenderId: '271736423528',
    projectId: 'ecoearn-7c0ca',
    storageBucket: 'ecoearn-7c0ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABsKenaH6SM2WaCV8yPlpAMsjw1HR_5_Q',
    appId: '1:271736423528:ios:d233d9867db4d1eff7e7dd',
    messagingSenderId: '271736423528',
    projectId: 'ecoearn-7c0ca',
    storageBucket: 'ecoearn-7c0ca.firebasestorage.app',
    iosBundleId: 'com.example.ecoearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABsKenaH6SM2WaCV8yPlpAMsjw1HR_5_Q',
    appId: '1:271736423528:ios:d233d9867db4d1eff7e7dd',
    messagingSenderId: '271736423528',
    projectId: 'ecoearn-7c0ca',
    storageBucket: 'ecoearn-7c0ca.firebasestorage.app',
    iosBundleId: 'com.example.ecoearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATV1DgIpplhUiy8XlQhgIzf3ZEn8WTesg',
    appId: '1:271736423528:web:61342ecd1801a0a8f7e7dd',
    messagingSenderId: '271736423528',
    projectId: 'ecoearn-7c0ca',
    authDomain: 'ecoearn-7c0ca.firebaseapp.com',
    storageBucket: 'ecoearn-7c0ca.firebasestorage.app',
  );
}
